### ISSUE TITLE
Error trying to register

### ISSUE THREAD

**Issue by punkouter2021** [RobertDyball/A2SPA#4]
Any idea what to look at?  

on this line

 var result = await _userManager.CreateAsync(user, model.Password);

I'm using your code. 

ReferenceError: _userManager is not defined
    at eval (eval at <anonymous> (http://localhost:57738/app/register.component.js), <anonymous>:1:1)
    at SafeSubscriber.eval [as _error] (http://localhost:57738/app/register.component.js:47:13)
    at SafeSubscriber.__tryOrUnsub (http://localhost:57738/node_modules/rxjs/Subscriber.js:223:16)
    at SafeSubscriber.error (http://localhost:57738/node_modules/rxjs/Subscriber.js:184:26)
    at Subscriber._error (http://localhost:57738/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (http://localhost:57738/node_modules/rxjs/Subscriber.js:102:18)
    at XMLHttpRequest.onLoad (http://localhost:57738/node_modules/@angular/http/bundles/http.umd.js:1185:38)
    at ZoneDelegate.invokeTask (http://localhost:57738/node_modules/zone.js/dist/zone.js:367:31)
    at Object.onInvokeTask (http://localhost:57738/node_modules/@angular/core/bundles/core.umd.js:3971:41)
    at ZoneDelegate.invokeTask (http://localhost:57738/node_modules/zone.js/dist/zone.js:366:36)
    at Zone.runTask (http://localhost:57738/node_modules/zone.js/dist/zone.js:166:47)
    at XMLHttpRequest.ZoneTask.ZoneTask.cancelFn.invoke (http://localhost:57738/node_modules/zone.js/dist/zone.js:420:38)

**Comment by RobertDyball** [comment]
Hey @punkouter did you get this working? 
If not, which branch were you trying?
